import {
  Banknote,
  CreditCard,
  MessageCircle,
  MapPin,
  CalendarCheck,
  Lock,
  PackageCheck,
  Truck,
  Gift,
  Percent,
  Star,
  Heart,
  ShieldCheck,
  Clock,
  Phone,
  Mail,
  Sparkles,
  Award,
  ThumbsUp,
  Users,
  Package,
  Headset,
  Wallet,
  BadgeCheck,
  Smile,
  Leaf,
  Droplet,
  Palette,
  Scissors,
  Gem,
  Zap,
  ShoppingBag,
  ShoppingCart,
  RefreshCw,
  Globe,
  Flame,
  type LucideIcon,
} from "lucide-react";

// Keys match Tamar_Home_Page_Settings::FEATURE_ICON_CHOICES on the WP side
// (wp-admin → הגדרות תמר → ניהול דף הבית → רצועת יתרונות).
const FEATURE_ICON_MAP: Record<string, LucideIcon> = {
  banknote: Banknote,
  "credit-card": CreditCard,
  "message-circle": MessageCircle,
  "map-pin": MapPin,
  "calendar-check": CalendarCheck,
  lock: Lock,
  "package-check": PackageCheck,
  truck: Truck,
  gift: Gift,
  percent: Percent,
  star: Star,
  heart: Heart,
  "shield-check": ShieldCheck,
  clock: Clock,
  phone: Phone,
  mail: Mail,
  sparkles: Sparkles,
  award: Award,
  "thumbs-up": ThumbsUp,
  users: Users,
  package: Package,
  headset: Headset,
  wallet: Wallet,
  "badge-check": BadgeCheck,
  smile: Smile,
  leaf: Leaf,
  droplet: Droplet,
  palette: Palette,
  scissors: Scissors,
  gem: Gem,
  zap: Zap,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  "refresh-cw": RefreshCw,
  globe: Globe,
  flame: Flame,
};

export function getFeatureIcon(key: string): LucideIcon {
  return FEATURE_ICON_MAP[key] ?? Sparkles;
}
